### ISSUE TITLE
Display file lineage

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renga-ui#159]
Renga will get a CD task that will generate a representation of the lineage of all data and output files in the repository.  This will be available as a Graphviz dot file.

On the file page, we should use the Graphviz dot file to display a navigable either list of graph.

See:

- https://github.com/gmamaladze/d3-dot-graph
- https://github.com/magjac/d3-graphviz

--- 
addresses https://github.com/SwissDataScienceCenter/renga/issues/146

**Comment by jirikuncar** [comment]
With https://github.com/SwissDataScienceCenter/renga/pull/158 you can check the environment called `dot/{ref}` to get a URL pointing to an artefact with the graph representation.

**Comment by ciyer** [comment]
Closed by #169.
