### ISSUE TITLE
do not use the navigation endpoints in UI

### ISSUE THREAD

**Issue by erbou** [SwissDataScienceCenter/renga-ui#30]
- [ ] identify tasks  
- [ ] change UI to invoke explorer 
- [ ] remove navigation from docker-compose
- [ ] remove navigation from Makefile
- [ ] make repo private?

**Comment by rokroskar** [comment]
@ebiiii is this done already? I seem to recall there was some refactoring taking place, but maybe this issue wasn't being referenced?

**Comment by ableuler** [comment]
@rokroskar no, navigation endpoints are still used to load the graph. I would switch to the explorer endpoints only after all API refactoring has been done.
