### ISSUE TITLE
Enable adding labels to nodes through the UI

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renga-ui#57]
Need more meta-data for the search (annotations, with minimal impact on type systems, use existing types with text labels)

**Comment by jirikuncar** [comment]
We can follow a pattern that is already used by deployer: `renga.<service/object>.<attribute>[.<name>][=<value.]` The only question is if we want to allow mutation of the labels at this stage.

**Comment by leafty** [comment]
Label editing on files has been merged.
For searches on the explorer side, you may have to make an issue. Otherwise, if it's happening on the ui side, then you can experiment :)

**Comment by ableuler** [comment]
Done for the files, see #80 for contexts.
