### ISSUE TITLE
Needs a decl statement

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renga-ui#72]
https://github.com/SwissDataScienceCenter/renga-ui/blob/9de740ac44ac46ac6e73b31ca2e526dca979f103/src/components/graph/index.ts#L78

Should be 

`const dispatcher = d3.dispatch('collapse')`
or
`let dispatcher = d3.dispatch('collapse')`

**Comment by ableuler** [comment]
You must have missed my reply to your review on PR #68 

> Didn't see it either when we looked at it, but this is actually still part of the GraphComponent class declaration. I moved it further up so it comes before all the methods (where one would expect it).
